env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
globals:
  {
    require: readonly,
    module: readonly,
    '__dirname': readonly,
    chrome: readonly,
    process: readonly,
  }
ignorePatterns:
  - "build"
  - "node_modules"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  spaced-comment:
    - error
    - always
  object-curly-spacing:
    - error
    - always
